[package]
name = "isobar_wasm"
version = "0.1.0"
authors = ["Josh Cooper <ugtstreamer@ex.ua>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.1"
wasm-bindgen = "0.2"

[features]
js-tests = []
