[package]
name = "isobar"
version = "0.1.0"
authors = ["Vlad Hashimoto <ukrgametactics@ex.ua>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
isobar_core = {path = "../isobar_core"}
covalent = {path = "../../covalent"}
