[package]
name = "isobar"
version = "0.1.0"
authors = ["Vlad Hashimoto <ukrgametactics@ex.ua>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
isobar-core = {path = "./isobar-core"}
collider = {path = "../collider"}

[workspace]
