[package]
name = "napi"
version = "0.1.0"
authors = ["Vlad Hashimoto <ukrgametactics@ex.ua>"]
license = "MIT"

[dependencies]
futures = "0.1.17"

[build-dependencies]
bindgen = "0.32.1"
cc = "1.0"
glob = "0.2.11"
