[package]
name = "nano"
version = "0.1.0"
authors = ["Josh Cooper <ugtstreamer@ex.ua>", "Vlad Hashimoto <hashimoto.stream@gmail.com>"]

[dependencies]
futures = "0.1"
smallvec = "0.6.1"
parking_lot = "0.6"
uuid = { version = "0.6", features = ["v4"] }

[dev-dependencies]
rand = "0.3"
