version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest-node-browsers-legacy
      - image: circleci/node:latest-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build
          command: ./script/cibuild


