#!/usr/bin/env bash

mkdir -p dist
CARGO_INCREMENTAL=0 RUSTFLAGS="-C debuginfo=0 -C opt-levels=s -C lto -C panic=abort" cargo build --release --target wasm32-unknown-unknown
wasm-bindgen ../target/wasm32-unknown-unknown/release/isobar_wasm.wasm --out-dir dist
wasm-opt -O3 ./dist/isobar_wasm_bg.wasm ./dist/isobar_wasm_bg.wasm
