#!/usr/bin/env bash

mkdir -p dist
CARGO_INCREMENTAL=0 RUSTFLAGS="-C debuginfo=0 -C opt-levels=s -C lto -C panic=abort" cargo +nightly build --release --target wasm32-unknown-unknown
wasm-bindgen ../target/wasm32-unknown-unknown/release/isobar_wasm.wasm --out-dir dist
