[package]
name = "ocean"
version = "0.1.0"
authors = ["Josh Cooper <ugtstreamer@ex.ua>", "Vlad Hashimoto <hashimoto.stream@gmail.com>"]

[dependencies]
smallvec = "0.6.1"
parking_lot = "0.5"

[dev-dependencies]
rand = "0.3"
